# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20190111_1920'),
        ('sitesettings', '0002_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL путь')),
            ],
            options={
                'verbose_name': 'Актуальное',
                'verbose_name_plural': 'Актуальное',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
