# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_contact_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.URLField(max_length=500, null=True, verbose_name='Локация'),
        ),
    ]
