# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='adults',
            field=models.PositiveIntegerField(verbose_name='Количество взрослых'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='check_in',
            field=models.DateField(verbose_name='Заезд'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='check_out',
            field=models.DateField(verbose_name='Отъезд'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='children',
            field=models.PositiveIntegerField(verbose_name='Количество взрослых'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Время бронирования'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='rooms',
            field=models.PositiveIntegerField(verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='adults',
            field=models.PositiveIntegerField(verbose_name='Количество взрослых'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='check_in',
            field=models.DateField(verbose_name='Заезд'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='check_out',
            field=models.DateField(verbose_name='Отъезд'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='children',
            field=models.PositiveIntegerField(verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Время бронирования'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='bookingtour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Tour', verbose_name='Тур'),
        ),
    ]
