# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='sale',
        ),
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=1),
        ),
    ]
