# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190111_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourday',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Tour'),
        ),
    ]
