# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190111_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='comment/image/%Y/%m/%d/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotel/image/%Y/%m/%d/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=1, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Строка'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='summary',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sale',
            field=models.PositiveIntegerField(verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Hotel', verbose_name='Гостиница'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='room/image/%Y/%m/%d/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Строка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=255, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='slide/image/%Y/%m/%d/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='tour/image/%Y/%m/%d/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=1, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Строка'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='view',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='day',
            field=models.PositiveIntegerField(default=0, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='preview',
            field=models.ImageField(upload_to='tourday/preview/%Y/%m/%d/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Tour', verbose_name='Тур'),
        ),
    ]
