# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190111_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image_3d',
            field=models.URLField(blank=True, null=True, verbose_name='3D изображение'),
        ),
    ]
