# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20190111_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Category', verbose_name='Категория'),
        ),
    ]
