# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20190111_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourday',
            options={'ordering': ['id'], 'verbose_name': 'Программа дня', 'verbose_name_plural': 'Программа дней'},
        ),
    ]
